src/Entity/Freezer.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FreezerRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Freezer
{
    use DefaultDatetimeTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\House", inversedBy="freezers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $house;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FreezerItem", mappedBy="freezer")
     */
    private $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getName()
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return House|null
     */
    public function getHouse()
    {
        return $this->house;
    }

    public function setHouse(House $house = null): self
    {
        $this->house = $house;

        return $this;
    }

    /**
     * @return Collection|FreezerItem[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    /**
     * @return Collection|FreezerItem[]
     */
    public function getActualItems(): Collection
    {
        $criteria = Criteria::create();
        $criteria->where(Criteria::expr()->isNull('dateRemoval'));

        return $this->items->matching($criteria);
    }

    public function addItem(FreezerItem $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setFreezer($this);
        }

        return $this;
    }

    public function removeItem(FreezerItem $item): self
    {
        if ($this->items->contains($item)) {
            $this->items->removeElement($item);
            // set the owning side to null (unless already changed)
            if ($item->getFreezer() === $this) {
                $item->setFreezer(null);
            }
        }

        return $this;
    }
}

src/Controller/FreezerController.php
<?php

namespace App\Controller;

use App\Entity\Freezer;
use App\Entity\FreezerItem;
use App\Entity\User;
use App\Form\FreezerItemType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\RouterInterface;

/**
 * Class MenuController
 *
 * @package App\Controller
 *
 * @Route("/freezer", name="freezer_")
 */
class FreezerController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function home(): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $house = $user->getHouse();

        if ($house === null) {
            return $this->redirectToRoute('new_house');
        }

        return $this->render('freezer/index.html.twig', ['house' => $house]);
    }

    /**
     * @Route("/new", name="new")
     */
    public function newFreezer(Request $request, EntityManagerInterface $manager)
    {
        /** @var User $user */
        $user = $this->getUser();
        $house = $user->getHouse();

        if ($house === null) {
            return $this->redirectToRoute('home');
        }

        $form = $this->createFormBuilder(new Freezer())
            ->add('name', TextType::class)
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $freezer = $form->getData();
            $freezer->setHouse($house);
            $manager->persist($freezer);
            $manager->flush();

            return $this->redirectToRoute('freezer_freezer', ['id' => $freezer->getId()]);
        }

        return $this->render('freezer/new-freezer.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/{id}", name="freezer")
     */
    public function freezer(Freezer $freezer, RouterInterface $router): Response
    {
        $freezerNav = [];
        foreach ($freezer->getHouse()->getFreezers() as $ent) {
            $freezerNav[$ent->getName()] = $router->generate('freezer_freezer', ['id' => $ent->getId()]);
        }

        return $this->render(
            'freezer/freezer.html.twig',
            ['freezer' => $freezer, 'freezerNav' => $freezerNav]
        );
    }

    /**
     * @Route("{id}/item/add", name="item_add", methods={"POST"})
     * @param Freezer $freezer
     * @param Request $request
     * @param EntityManagerInterface $manager
     *
     * @return Response|JsonResponse
     * @throws \Exception
     */
    public function addItem(Freezer $freezer, Request $request, EntityManagerInterface $manager)
    {
        /** @var User $user */
        $user = $this->getUser();

        $item = new FreezerItem();
        $item->setFreezer($freezer);
        $item->setDateExpiry(new \DateTime());
        $item->setCreator($user);

        $url = $this->generateUrl('freezer_item_add', ['id' => $freezer->getId()]);

        $form = $this->createForm(FreezerItemType::class, $item, ['action' => $url]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var FreezerItem $item */
            $item = $form->getData();
            $item->setFreezer($freezer);
            $manager->persist($item);
            $manager->flush();
            $this->addFlash('success', 'New item added to freezer');

            return $this->redirectToRoute('freezer_freezer', ['id' => $freezer->getId()]);
        }

        return $this->render('freezer/item-form.html.twig', ['freezerItemForm' => $form->createView(), 'submitValue' => 'Add']);
    }

    /**
     * @Route("/item/update/{id}", name="item_update", methods={"POST"})
     * @param FreezerItem $item
     * @param Request $request
     * @param EntityManagerInterface $manager
     *
     * @return Response|JsonResponse
     */
    public function updateItem(FreezerItem $item, Request $request, EntityManagerInterface $manager)
    {
        $url = $this->generateUrl('freezer_item_update', ['id' => $item->getId()]);

        $form = $this->createForm(FreezerItemType::class, $item, ['action' => $url]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var FreezerItem $item */
            $item = $form->getData();

            // Quantity equals to zero means item must be removed
            if ($item->getQuantity() === 0) {
                return $this->redirectToRoute('freezer_item_remove', ['id' => $item->getId()], 307);
            }

            $manager->flush();
            $this->addFlash('success', 'Item updated');

            return $this->redirectToRoute('freezer_freezer', ['id' => $item->getFreezer()->getId()]);
        }

        return $this->render('freezer/item-form.html.twig', ['freezerItemForm' => $form->createView(), 'submitValue' => 'Update']);
    }

    /**
     * @Route("/item/remove/{id}", name="item_remove", methods={"POST"})
     * @param FreezerItem $item
     * @param Request $request
     * @param EntityManagerInterface $manager
     *
     * @return Response|JsonResponse
     * @throws \Exception
     */
    public function removeItem(FreezerItem $item, Request $request, EntityManagerInterface $manager)
    {
        $item->setDateRemoval(new \DateTime('now'));
        $manager->flush();
        $this->addFlash('success', 'Item removed');

        return $this->redirectToRoute('freezer_freezer', ['id' => $item->getFreezer()->getId()]);
    }
}

templates/freezer/freezer.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ freezer.name ? freezer.name : 'freezer' | capitalize }}{% endblock %}

{% block page_title %}Freezer{% endblock %}

{% block page_content %}
    <div class="container">
        <h3>Let's see what's in {{ freezer.name ? freezer.name : 'this freezer' }}</h3>
        <p class="flex-row align-items-center">
            <svg class="icon" id="i-info" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="16" height="16" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                <path d="M16 14 L16 23 M16 8 L16 10" />
                <circle cx="16" cy="16" r="14" />
            </svg>
            Click on an item to adjust quantity or remove it.
        </p>
        <div class="col-12 no-gutters row">
            <div class="col-sm-4 text-center freezer-item">
                <a class="app-link" id="myBtn" href="{{ path('freezer_item_add', {id: freezer.id}) }}">
                    <h5 class="row align-items-center justify-content-center">Add item</h5>
                    <svg id="i-plus" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                        <path d="M16 2 L16 30 M2 16 L30 16" />
                    </svg>
                </a>
            </div>
            {% for item in freezer.actualItems %}
                <div class="col-sm-4 text-center freezer-item">
                    <a class="app-link" href="{{ path('freezer_item_update', { id: item.id }) }}">
                        <h5 class="row align-items-center justify-content-center {{ (item.hasExpired) ? 'text-color-secondary' }}">
                            {{ item.category.name ~ ' ' }}
                            {% if item.expiresSoon %}
                                <svg id="i-flag" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="16" height="16" fill="none" stroke="#dd6e42" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5">
                                    <path d="M6 2 L6 30 M6 6 L26 6 20 12 26 18 6 18" />
                                </svg>
                            {% endif %}
                            {% if item.hasExpired %}
                                <svg id="i-ban" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="16" height="16" fill="none" stroke="#dd6e42" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                                    <circle cx="16" cy="16" r="14" />
                                    <path d="M6 6 L26 26" />
                                </svg>
                            {% endif %}
                        </h5>
                        <svg id="i-bag" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                            <path d="M5 9 L5 29 27 29 27 9 Z M10 9 C10 9 10 3 16 3 22 3 22 9 22 9" />
                        </svg>
                        <p class="text-small">{{ item.description }}</p>
                        <p class="text-smaller">{{ item.quantity ~ ' ' ~ item.unit }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
        <div class="col-xs full-width bottom-navbar" style="flex-direction: row;display: flex;justify-content: space-around;">
            {% for name, link in freezerNav %}
                <div class="col-xs-2 navbar-link" style="padding: 7px;">
                    <a href="{{ link }}">
                        <svg id="i-archive" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="16" height="16" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                            <path d="M4 10 L4 28 28 28 28 10 M2 4 L2 10 30 10 30 4 Z M12 15 L20 15" />
                        </svg>
                        <p>{{ name }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    {#  modal for new item / edit item  #}
    <div  id="myModal" class="modal">
        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <p>Some text in the Modal..</p>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
{{ parent() }}
    <script>
        window.onload = function() {
            // Get modal, modal content and close button
            const modal = document.getElementById("myModal");
            const modalContent = modal.querySelector(".modal-content p");
            const closeModalSpan = modal.getElementsByClassName("close")[0];

            const items = document.querySelectorAll(".freezer-item a");

            // Each item will open modal, with form in it
            for (item of items) {
                item.onclick = function(event) {
                    event.preventDefault();
                    modal.style.display = "block";
                    xhr.open('POST', this.href);
                    xhr.send();
                }
            }

            // When the user clicks on <span> (x), close the modal
            closeModalSpan.onclick = function() {
                modal.style.display = "none";
            };

            // When the user clicks anywhere outside of the modal, close it
            window.onclick = function(event) {
                if (event.target == modal) {
                    modal.style.display = "none";
                }
            };

            // Set up our HTTP request
            const xhr = new XMLHttpRequest();

            // Setup our listener to process completed requests
            xhr.onload = function () {

                // Process our return data
                if (xhr.status >= 200 && xhr.status < 300) {
                    // What do when the request is successful
                    modalContent.innerHTML = xhr.response;

                    category = document.getElementById('freezer_item_category');
                    dateExpiryInput = document.getElementById('freezer_item_dateExpiry');

                    // Update automatically expiry date when changing item's category
                    category.onchange = function(event) {
                        defaultValidity = event.target.options[event.target.options.selectedIndex].dataset.defaultValidity;
                        
                        dateExpiry = new Date();
                        dateExpiry.setDate(dateExpiry.getDate() + parseInt(defaultValidity));
                        
                        dateExpiryFormatted = dateExpiry.getFullYear();
                        dateExpiryFormatted += '-' + ('0' + (dateExpiry.getMonth()+1)).slice(-2);
                        dateExpiryFormatted += '-' + ('0' + dateExpiry.getDate()).slice(-2);

                        dateExpiryInput.value = dateExpiryFormatted;
                    }
                } else {
                    // What do when the request fails
                    console.log('The request failed!');
                    console.log(xhr.status);
                    console.log(xhr.response);
                }

                // Code that should run regardless of the request status
                // console.log('This always runs...');
            };
        };
    </script>
{% endblock %}

templates/freezer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Freezer{% endblock %}

{% block page_title %}
    Freezer
{% endblock %}

{% block page_content %}

    <div class="col-6 text-center">
        <h4>Freezer</h4>
        {% if house.freezers is not empty %}
            {% for freezer in house.freezers %}
                <a href="{{ path('freezer_freezer', {id: freezer.id}) }}">
                    <svg id="i-archive" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                        <path d="M4 10 L4 28 28 28 28 10 M2 4 L2 10 30 10 30 4 Z M12 15 L20 15" />
                    </svg>
                    <p>{{ freezer.name }}</p>
                </a>
            {% endfor %}
        {% endif %}
        <a href="{{ path('freezer_new') }}">
            <svg id="i-plus" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                <path d="M16 2 L16 30 M2 16 L30 16" />
            </svg>
        </a>
    </div>
{% endblock %}

templates/freezer/item-form.html.twig
{{ form_start(freezerItemForm) }}
<div class="row">
    <div class="col-12">
        {{ form_row(freezerItemForm.category) }}
    </div>
    <div class="col-12">
        {{ form_row(freezerItemForm.description) }}
    </div>
    <div class="col-12">
        {{ form_label(freezerItemForm.dateExpiry) }}
        {{ form_widget(freezerItemForm.dateExpiry) }}
    </div>
    <div class="col-12 inline-text-and-select">
        {{ form_widget(freezerItemForm.quantity) }} {{ form_widget(freezerItemForm.unit) }}
    </div>
    {% if freezerItemForm.freezer is defined %}
        <div class="col-12 inline-text-and-select">
{#            {{ form_rest(freezerItemForm) }}#}
            {{ form_label(freezerItemForm.freezer) }} {{ form_widget(freezerItemForm.freezer) }}
        </div>
    {% endif %}
    {{ form_rest(freezerItemForm) }}
    <div class="col-12">
        <input type="submit" value="{{ submitValue }}">
    </div>
</div>
{{ form_end(freezerItemForm) }}
{% if is_granted('remove', freezerItemForm.vars.value) %}
    <div class="col-12">
        <form action="{{ path('freezer_item_remove', {id: freezerItemForm.vars.value.id}) }}" method="post">
            <input type="submit" value="Remove" id="removeFreezerItem">
        </form>
    </div>
{% endif %}

<script>
</script>

templates/freezer/new-freezer.html.twig
{% extends 'base.html.twig' %}

{% block title %}New freezer{% endblock %}

{% block page_title %}New freezer{% endblock %}
{% block page_content %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <input type="submit" value="GO!">
    {{ form_end(form) }}
{% endblock %}

templates/freezer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <input type="submit" value="GO!">
    {{ form_end(form) }}
{% endblock %}